apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-gaming-deployment
  namespace: lugx-gaming
  labels:
    app: lugx-gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lugx-gaming
  template:
    metadata:
      labels:
        app: lugx-gaming
    spec:
      containers:
      - name: lugx-gaming-container
        image: joyvinensius/lugx_gaming:1.0.2  # Menggunakan tag build dari Jenkins
        ports:
        - containerPort: 80