apiVersion: v1
kind: Service
metadata:
  name: lugx-gaming-service
  namespace: lugx-gaming
  labels:
    app: lugx-gaming
spec:
  type: LoadBalancer
  selector:
    app: lugx-gaming
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80